# Generated by Django 3.1.3 on 2020-12-05 09:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20201205_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile pic'),
        ),
    ]
