# Generated by Django 3.1.3 on 2020-12-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20201202_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='businessEmail',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='businessName',
            new_name='business_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='', verbose_name='profile pic'),
        ),
    ]
